# Application Configuration
server.port=8080

# H2 Database Configuration (File-based persistence)
spring.datasource.url=jdbc:h2:file:./db/chanakyaiq;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate / JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Google OAuth2 Settings (Requires Client ID / Client Secret to be set by User)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:524346453272-bj7h5e693hlcvif9jihk0v6q7afairrq.apps.googleusercontent.com}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET: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}
spring.security.oauth2.client.registration.google.scope=profile,email
 
# Upstox API Settings
chanakyaiq.api.token=${UPSTOX_API_TOKEN:eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIyMTk3MDQiLCJqdGkiOiI2YTJkYmU4Y2I0OTVmNjIyNDkwZGY4Y2QiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6dHJ1ZSwiaWF0IjoxNzgxMzgyNzk2LCJpc3MiOiJ1ZGFwaS1nYXRld2F5LXNlcnZpY2UiLCJleHAiOjE3ODEzODgwMDB9.-b913YgJv29Bq4awesSZSf2Y0R9KbErC1OVBcjOs2mw}

# Generic REST Client Configuration
rest.client.timeout.connect=5000
rest.client.timeout.read=5000
rest.client.pool.max-total=50
rest.client.pool.default-max-per-route=20
